df = pd.read_csv("/workspaces/python-for-finance-bobby-zlatarov/DASH.csv")

df
df["Date"] = pd.to_datetime(df["Date"])
df = df.set_index("Date").sort_index()

In [5]:
df = pd.read_csv("/workspaces/python-for-finance-bobby-zlatarov/DASH.csv")

df
df["Date"] = pd.to_datetime(df["Date"])
df = df.set_index("Date").sort_index()
df

/tmp/ipykernel_51285/2281826311.py:4: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"] = pd.to_datetime(df["Date"])

                 Close        High         Low        Open      Volume
Date
2020-12-09  189.509995  195.500000  163.800003  182.000000  25373700.0
2020-12-10  186.000000  187.695007  172.636002  179.710007         NaN
2020-12-11  175.000000  182.000000  168.250000  176.520004   4760600.0
2020-12-14  160.000000  170.000000  151.199997  169.100006   7859600.0
2020-12-15  158.889999  161.419998  153.759995  157.100006   5017000.0
...                ...         ...         ...         ...         ...
2025-06-09  217.490005  219.830002  216.955002  218.029999   2710300.0
2025-06-10  214.970001  219.210007  210.927002  216.589996   3916700.0
2025-06-11  217.800003  219.529999  212.240005  214.184998   3091500.0
2025-06-12  216.600006  219.419998  215.675003  218.080002   2510400.0
2025-06-13  218.119995  218.299896  213.000000  214.190002    616326.0

[1184 rows x 5 columns]